name: Deploy Le Moulin

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Installer les dépendances
        working-directory: frontend
        run: npm ci

      - name: Build SvelteKit
        working-directory: frontend
        run: npm run build

      - name: Déployer sur le serveur
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "frontend/build/"
          TARGET: "/home/samit/lemoulin"

      - name: Déployer package.json
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "frontend/package.json frontend/package-lock.json"
          TARGET: "/home/samit/lemoulin"

      - name: Déployer les migrations PocketBase
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          SOURCE: "backend/pb_migrations/"
          TARGET: "/opt/pocketbase"

      - name: Installer dépendances et redémarrer
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                  cd /home/samit/lemoulin
                  npm install --production
                  sudo systemctl restart lemoulin --no-pager
                  sudo systemctl restart pocketbase --no-pager